# Generated by Django 3.2 on 2024-11-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_libro_cantidad_disponible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='cantidad_disponible',
            new_name='cantidad',
        ),
        migrations.AddField(
            model_name='libro',
            name='restriccion_edad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
