# Generated by Django 3.2 on 2024-12-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_alter_prestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de entrega'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('Ficción', 'Ficción'), ('No ficción', 'No ficción'), ('Misterio', 'Misterio'), ('Ciencia ficción', 'Ciencia ficción'), ('Fantasía', 'Fantasía'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Biografía', 'Biografía'), ('Historia', 'Historia'), ('Ciencia', 'Ciencia'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
