# Generated by Django 3.2 on 2024-12-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_auto_20241204_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='genero_personalizado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
