# Generated by Django 3.2 on 2024-12-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0009_auto_20241207_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
